// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Sidebar from "@/components/dashboard/Sidebar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="bg-[#0f0f0f]">
//         <div className="relative">
//   {/* <div className="absolute inset-0 bg-[radial-gradient(circle_at_top,rgba(120,0,255,0.15),transparent_70%)]"></div>
//   <div className="flex">
//   <Sidebar />
//   <main className="flex-1 p-6">{children}</main>
// </div> */}
// {/* <div className="absolute inset-0 bg-[radial-gradient(circle_at_top,rgba(120,0,255,0.15),transparent_70%)] -z-10"></div> */}
// <div className="fixed inset-0 bg-[radial-gradient(...)] pointer-events-none -z-50" />

// <div className="relative z-10 flex">
//   <Sidebar />
//   <main className="flex-1 p-6">{children}</main>
// </div>
// </div>
//       </body>
//     </html>
//   );
// }










import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/dashboard/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "DD - Discipline Dashboard",
//   description: "Discipline = Freedom",
// };

export const metadata: Metadata = {
  title: "DD - Discipline Dashboard",
  description: "Discipline = Freedom",
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "DD Dashboard",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="bg-[#0f0f0f] text-white selection:bg-purple-500/30">
        {/* Фоновый градиент (теперь с корректным цветом и фиксацией) */}
        <div className="fixed inset-0 bg-[radial-gradient(circle_at_top,rgba(120,0,255,0.1),transparent_70%)] pointer-events-none -z-50" />

        <div className="relative flex min-h-screen">
          {/* Наш адаптивный сайдбар */}
          <Sidebar />

          {/* Главный блок контента */}
          <main className="
            flex-1 
            transition-all duration-300
            
            /* --- ДЕСТКОП (от 768px) --- */
            /* md:ml-64 отодвигает контент от фиксированного сайдбара */
            md:ml-64 
            md:p-10
            
            /* --- МОБИЛКА --- */
            p-4
            /* pb-32 чтобы нижнее меню не перекрывало контент (80px + запас) */
            pb-32 
            md:pb-10
          ">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}





